### ISSUE TITLE
Torrent file validation method

### ISSUE THREAD

**Issue by d47081** [Rhilip/Bencode#14]
It could be useful to have build-in method for uploaded files validation 

```
true === \Rhilip\Bencode\TorrentFile::isValid($filepath);
```

Because getting an exception with 500 code on load PNG file (as example of wrong file type)

```
$torrent = \Rhilip\Bencode\TorrentFile::load($filepath);

Invalid integer format or integer overflow: �PNG
```

For right now, I'm using external construction like this

```
    public function isValid(
        string $filepath
    ): bool
    {
        try
        {
            \Rhilip\Bencode\TorrentFile::load(
                $filepath
            );
        }

        catch (\Rhilip\Bencode\ParseException $error)
        {
            return false;
        }

        return true;
    }
```

p.s. thanks for your work!

**Comment by Rhilip** [comment]
`TorrentFile::load` only check the exist and type of `$->info`, `$->info->piece length`, `$->info->name`, as those keys **MUST** exist. 
some deep invalid of torrent file will not check in construct. so I wrote the current step to check torrent is real valid or not in README.

```php
try {
    $torrent = TorrentFile::load($_POST['torrent']['tmp_name']);
    $torrent/** ->setParseValidator(function () {}) */->parse();
} catch (ParseException $e) {
    // do something to notice user.
}
```

> Note: `->parse()` to check the deep invalid will cause extra io, and a customer method (`->setParseValidator(function () {})`) is provided to break parse process.

In this case, I don't think `isValid` in your example code is enough and it may mislead other users.
